# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
- openssl aes-256-cbc -K $encrypted_39c05ab0bd98_key -iv $encrypted_39c05ab0bd98_iv
  -in tests/testthat/twitter_tokens.enc -out tests/testthat/twitter_tokens -d
after_success:
  - bash <(curl -s https://codecov.io/bash)
